version: "3"

services:
  web:
    image: docker.io/paveu/apimocker:latest
    depends_on:
      - cache
      - celery
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
    # Values present in the environment at runtime will always override those defined inside the .env file.
    # Similarly, values passed via command-line arguments take precedence as well.
    # .env file must be created with following env variables
      - ENVIRONMENT=production
      - DATABASE_MOCKER_URL
      - RAVEN_CONFIG_DSN
    ports:
      - "8000:8443"
    volumes:
      - .:/app
    command: /base/entry web
    networks:
      - webnet
  cache:
    image: redis
    ports:
      - "6379:6379"
    # Make sure your shell is configured to talk to default.
    # Create a ./data directory on the manager:
    # docker-machine ssh default "mkdir ./data"
    # The volume you created that lets the container access ./data (on the host)
    # as /data (inside the Redis container). While containers come and go,
    # the files stored on ./data on the specified host will persist, enabling continuity.
    volumes:
      - esdata:/redis_data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
  celery:
    image: docker.io/paveu/apimocker:latest
    depends_on:
      - cache
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - ENVIRONMENT=production
      - DATABASE_MOCKER_URL
      - RAVEN_CONFIG_DSN
    volumes:
      - .:/app
    command: /base/entry celery_worker_and_beat
    networks:
      - webnet
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    networks:
      - webnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    volumes:
      - ./apimocker/settings/external/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
#        constraints:
#          - node.hostname == myvm1
    networks:
      - webnet
  logstash:
    hostname: logstash
    image: docker.elastic.co/logstash/logstash:5.6.3
    command: -f /usr/share/logstash/pipeline/logstash.conf
    volumes:
        - ./apimocker/settings/external/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        - ./apimocker/settings/external/logstash/pipeline/patterns:/etc/logstash/patterns.d
        - ./apimocker/settings/external/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
        - "5000:5000/tcp"
        - "5044:5044/tcp"
        - "5000:5000/udp"
        - "5044:5044/udp"
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    volumes:
      - ./apimocker/settings/external/kibana/config:/usr/share/kibana/config
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
    driver: overlay
volumes:
  esdata:
    driver: local