version: "3"

services:
  traefik:
    image: traefik
    command: --web --docker --docker.swarmmode --docker.watch --docker.domain=example.com --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - frontend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.backend=traefik"
        - "traefik.port=8080"
        - "traefik.frontend.rule=PathPrefixStrip:/"
        - "traefik.frontend.rule=Host:lb.example.com"
        - "traefik.docker.network=frontend"
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
networks:
  frontend:
    external: true