# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=128, verbose_name='HTTP methods')),
                ('content_type', models.CharField(choices=[('application/json', 'application/json'), ('application/x-www-form-urlencoded', 'application/x-www-form-urlencoded'), ('application/xhtml+xml', 'application/xhtml+xml'), ('multipart/form-data', 'multipart/form-data'), ('text/css', 'text/css'), ('text/csv', 'text/csv'), ('text/html', 'text/html'), ('text/json', 'text/json'), ('text/plain', 'text/plain'), ('text/xml', 'text/xml')], max_length=256, verbose_name='Content types')),
                ('body', models.TextField(verbose_name='Body')),
            ],
            options={
                'verbose_name': 'API Mocker',
                'verbose_name_plural': 'API Mockers',
            },
        ),
    ]
