# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocker',
            name='destination_address',
            field=models.URLField(default=datetime.datetime(2016, 9, 14, 13, 8, 38, 26867, tzinfo=utc), verbose_name='Destination Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mocker',
            name='return_address',
            field=models.URLField(default=1, verbose_name='Return Address'),
            preserve_default=False,
        ),
    ]
