# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0002_auto_20160914_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocker',
            name='return_address',
            field=models.URLField(blank=True, null=True, verbose_name='Return Address'),
        ),
    ]
