# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0004_mocker_short_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocker',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mocker',
            name='updation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updation date'),
        ),
    ]
