# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0005_auto_20160914_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocker',
            name='short_id',
        ),
        migrations.AddField(
            model_name='mocker',
            name='mocked_address',
            field=models.URLField(blank=True, null=True, verbose_name='Mocked Address'),
        ),
    ]
