# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0006_auto_20160914_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocker',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='destination_address',
            field=models.URLField(verbose_name='Destination URL Address'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='mocked_address',
            field=models.URLField(blank=True, null=True, verbose_name='Mocked URL Address'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='return_address',
            field=models.URLField(blank=True, null=True, verbose_name='Return URL Address'),
        ),
    ]
