# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0007_auto_20160914_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocker',
            name='mocked_address',
        ),
        migrations.AddField(
            model_name='mocker',
            name='short_id',
            field=models.CharField(default=1, max_length=256, verbose_name='Short id'),
            preserve_default=False,
        ),
    ]
