# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0009_auto_20160914_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocker',
            name='http_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocker.HTTP_Methods', verbose_name='HTTP Method'),
        ),
    ]
