# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0011_auto_20160914_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocker',
            name='http_method',
        ),
        migrations.AddField(
            model_name='mocker',
            name='http_method',
            field=models.ManyToManyField(to='mocker.HTTP_Method', verbose_name='HTTP Methods'),
        ),
    ]
