# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0012_auto_20160914_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocker',
            name='content_type',
            field=models.CharField(choices=[('application/json', 'application/json'), ('application/x-www-form-urlencoded', 'application/x-www-form-urlencoded'), ('application/xhtml+xml', 'application/xhtml+xml'), ('multipart/form-data', 'multipart/form-data'), ('text/css', 'text/css'), ('text/csv', 'text/csv'), ('text/html', 'text/html'), ('text/json', 'text/json'), ('text/plain', 'text/plain'), ('text/xml', 'text/xml')], max_length=256, verbose_name='Allowed content type for mocked address'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='destination_address',
            field=models.URLField(verbose_name='Destination address to be mocked'),
        ),
        migrations.RemoveField(
            model_name='mocker',
            name='http_method',
        ),
        migrations.AddField(
            model_name='mocker',
            name='http_method',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default=1, max_length=256, verbose_name='Allowed HTTP method for mocked address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mocker',
            name='return_address',
            field=models.URLField(blank=True, null=True, verbose_name='Callback address for sending pushed return message'),
        ),
        migrations.DeleteModel(
            name='HTTP_Method',
        ),
    ]
