# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0014_auto_20160914_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocker',
            name='body',
        ),
        migrations.AlterField(
            model_name='mocker',
            name='destination_content_type',
            field=models.CharField(choices=[('application/json', 'application/json'), ('application/x-www-form-urlencoded', 'application/x-www-form-urlencoded'), ('application/xhtml+xml', 'application/xhtml+xml'), ('multipart/form-data', 'multipart/form-data'), ('text/css', 'text/css'), ('text/csv', 'text/csv'), ('text/html', 'text/html'), ('text/json', 'text/json'), ('text/plain', 'text/plain'), ('text/xml', 'text/xml')], max_length=256, verbose_name='Allowed content type for address to be mocked'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='http_method',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=256, verbose_name='Allowed HTTP method for an adress to be mocked'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='return_content_type',
            field=models.CharField(choices=[('application/json', 'application/json'), ('application/x-www-form-urlencoded', 'application/x-www-form-urlencoded'), ('application/xhtml+xml', 'application/xhtml+xml'), ('multipart/form-data', 'multipart/form-data'), ('text/css', 'text/css'), ('text/csv', 'text/csv'), ('text/html', 'text/html'), ('text/json', 'text/json'), ('text/plain', 'text/plain'), ('text/xml', 'text/xml')], max_length=256, verbose_name='Callback content type'),
        ),
    ]
