# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0015_auto_20160914_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mocker',
            options={'verbose_name': 'Mocked API', 'verbose_name_plural': 'Mocked APIs'},
        ),
        migrations.AlterField(
            model_name='mocker',
            name='destination_content_type',
            field=models.CharField(choices=[('application/json', 'application/json')], max_length=256, verbose_name='Allowed content type for address to be mocked'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET')], max_length=256, verbose_name='Allowed HTTP method for an adress to be mocked'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='return_content_type',
            field=models.CharField(choices=[('application/json', 'application/json')], max_length=256, verbose_name='Callback content type'),
        ),
    ]
