# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0016_auto_20160914_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocker',
            name='mocked_address',
            field=models.URLField(blank=True, null=True, verbose_name='Mocked API Address'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='destination_address',
            field=models.URLField(verbose_name='Destination API to be mocked'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='destination_content_type',
            field=models.CharField(choices=[('application/json', 'application/json')], max_length=256, verbose_name='Allowed content type for an API to be mocked'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET')], max_length=256, verbose_name='Allowed HTTP method for an API to be mocked'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='return_address',
            field=models.URLField(blank=True, null=True, verbose_name='Callback API'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='return_content_type',
            field=models.CharField(choices=[('application/json', 'application/json')], max_length=256, verbose_name='Callback API content type'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='short_id',
            field=models.CharField(max_length=128, verbose_name='Hashed ID'),
        ),
    ]
