# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0017_auto_20160914_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocker',
            name='destination_address',
            field=models.URLField(verbose_name='Destination API address to be mocked'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='destination_content_type',
            field=models.CharField(choices=[('application/json', 'application/json')], max_length=256, verbose_name='Allowed content type for a mocked API'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='http_method',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PATCH', 'PATCH')], max_length=256, verbose_name='Allowed HTTP method for a mocked API'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='return_address',
            field=models.URLField(blank=True, null=True, verbose_name='Callback API address'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='return_content_type',
            field=models.CharField(blank=True, choices=[('application/json', 'application/json')], max_length=256, null=True, verbose_name='Callback API content type'),
        ),
    ]
