# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0002_auto_20170718_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('headers', models.TextField(null=True, verbose_name='API Response')),
                ('content', models.TextField(null=True, verbose_name='API Response')),
                ('mocker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mocker.Mocker')),
            ],
            options={
                'verbose_name': 'Response Content',
                'verbose_name_plural': 'Response Contents',
            },
        ),
        migrations.RemoveField(
            model_name='responsecontent',
            name='mocker',
        ),
        migrations.DeleteModel(
            name='ResponseContent',
        ),
    ]
