# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0003_auto_20170718_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responselog',
            options={'verbose_name': 'Response Log', 'verbose_name_plural': 'Response logs'},
        ),
        migrations.RemoveField(
            model_name='mocker',
            name='response_data',
        ),
        migrations.AddField(
            model_name='mocker',
            name='response_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mocker.ResponseSetting'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='allowed_content_type',
            field=models.CharField(choices=[(b'application/json', 'application/json')], max_length=256, verbose_name='Allowed content type for mock'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='callback_address',
            field=models.URLField(blank=True, null=True, verbose_name='Callback address (Optional)'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='callback_content_type',
            field=models.CharField(blank=True, choices=[(b'application/json', 'application/json')], max_length=256, null=True, verbose_name='Callback content type (Optional)'),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='content',
            field=models.TextField(null=True, verbose_name='Response content'),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='headers',
            field=models.TextField(null=True, verbose_name='Response headers'),
        ),
        migrations.AlterField(
            model_name='responsesetting',
            name='content_type',
            field=models.CharField(choices=[(b'application/json', 'application/json')], max_length=256, verbose_name='Content type'),
        ),
    ]
