# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0004_auto_20171010_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('key', models.CharField(max_length=256, verbose_name='Key')),
                ('value', models.CharField(max_length=256, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Custom header',
                'verbose_name_plural': 'Custom headers',
            },
        ),
        migrations.AlterField(
            model_name='mocker',
            name='allowed_http_method',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'POST', b'POST'), (b'GET', b'GET'), (b'PATCH', b'PATCH'), (b'PUT', b'PUT'), (b'HEAD', b'HEAD'), (b'OPTIONS', b'OPTIONS')], max_length=31, verbose_name='Allowed HTTP method for mock'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='response_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mocker.ResponseSetting', verbose_name='Response settings (Optional)'),
        ),
        migrations.AddField(
            model_name='mocker',
            name='custom_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mocker.CustomHeader', verbose_name='Custom header (Optional)'),
        ),
    ]
