# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-02 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocker',
            name='callback_content_type',
            field=models.CharField(blank=True, choices=[('application/json', 'application/json'), ('text/plain', 'text/plain')], max_length=256, null=True, verbose_name='Callback API content type'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='mocked_allowed_content_type',
            field=models.CharField(choices=[('application/json', 'application/json'), ('text/plain', 'text/plain')], max_length=256, verbose_name='Mocked API allowed content type'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='mocked_allowed_http_method',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PATCH', 'PATCH'), ('PUT', 'PUT')], max_length=256, verbose_name='Mocked API allowed HTTP method'),
        ),
        migrations.AlterField(
            model_name='mocker',
            name='original_destination_address',
            field=models.URLField(verbose_name='Original API address'),
        ),
    ]
